added new files
morento101/Algo-Tasks pull request #7
Opened 2022-04-26 07:34 UTC by YaroslavBorysko

2022-04-26 20:17 UTC, Misha86 commented on tasks/task_178d.py
> +from math import factorial as fac
need empty string after module docstring

2022-04-26 20:18 UTC, Misha86 commented on tasks/task_178d.py
> +def task178d(n: int, arr: list) -> int:
change format docstring
"""Docstring.......
...........
"""

2022-04-26 20:19 UTC, Misha86 commented on tests/test_task_182.py
> +    """
change format docstring
"""Docstring.......
...........
"""

2022-04-26 20:19 UTC, Misha86 commented on tests/test_task_182.py
> +        """
change format docstring
"""Docstring.......
...........
"""

2022-04-26 20:19 UTC, Misha86 commented on tests/test_task_182.py
> +        """
change format docstring
"""Docstring.......
...........
"""

2022-04-26 20:19 UTC, Misha86 commented on tests/test_task_182.py
> +        """
change format docstring
"""Docstring.......
...........
"""

2022-04-26 20:19 UTC, Misha86 commented on tests/test_task_182.py
> +        """
change format docstring
"""Docstring.......
...........
"""

2022-04-26 20:19 UTC, Misha86 commented on tests/test_task_323.py
> +    """
change format docstring
"""Docstring.......
...........
"""

2022-04-26 20:20 UTC, Misha86 commented on tasks/task_555.py
> +"""Module with task 555"""
need empty string after module docstring

2022-04-26 20:20 UTC, Misha86 commented on tasks/task_178g.py
> +    """
change format docstring
"""Docstring.......
...........
"""

2022-04-26 20:20 UTC, Misha86 commented on tasks/task_555.py
> +    """
change format docstring
"""Docstring.......
...........
"""

2022-04-26 20:21 UTC, Misha86 commented on tests/test_task_182.py
> +"""Module with tests for task 182"""
need empty string

2022-04-26 20:21 UTC, therobotisnotatoy commented on tasks/task_178d.py
> +    return c
Empty line required at the end of file

2022-04-26 20:21 UTC, therobotisnotatoy commented on tasks/task_178d.py
> +"""Module with task 178d"""
Empty line after module doctoring

2022-04-26 20:21 UTC, therobotisnotatoy commented on tasks/task_178g.py
> +    return c
Is it ok to use a single character as a variable?

2022-04-26 20:21 UTC, therobotisnotatoy commented on tasks/task_555.py
> +
Redundant line

2022-04-26 20:21 UTC, therobotisnotatoy commented on tests/test_task_182.py
> +from tasks.tasks_182 import task_182
Split different groups of import by empty line

2022-04-26 20:21 UTC, Misha86 commented on tests/test_task_323.py
> +"""Module with tests for task 323"""
need empty string

2022-04-26 20:21 UTC, Misha86 commented on tests/test_task_323.py
> +        """
change format docstring
"""Docstring.......
...........
"""

2022-04-26 20:22 UTC, Misha86 commented on tests/test_task_323.py
> +        """
change format docstring
"""Docstring.......
...........
"""

2022-04-26 20:22 UTC, Misha86 commented on tests/test_task_560.py
> +class TestTask560(TestCase):
change format docstring
"""Docstring.......
...........
"""

2022-04-26 20:22 UTC, Misha86 commented on tests/test_task_560.py
> +"""Module with tests for task 560"""
need empty string

2022-04-26 20:22 UTC, Misha86 commented on tests/test_task_323.py
> +    """
need empty string

2022-04-26 20:23 UTC, Misha86 commented on tests/test_task_560.py
> +    """
need empty string

2022-04-26 20:23 UTC, Misha86 commented on tests/test_task_560.py
> +        """
change format docstring
"""Docstring.......
...........
"""

2022-04-26 20:23 UTC, Misha86 commented on tests/test_task_560.py
> +        """
change format docstring
"""Docstring.......
...........
"""

2022-04-26 20:24 UTC, Misha86 reviewed
change format docstring
"""Docstring.......
...........
"""
add empty strings after test`s docstring

2022-04-28 11:22 UTC, morento101 commented on tasks/task_178d.py
> +    """ Return number that satisfy a following condition:
Stick to the task naming convention task_<task_number>

2022-04-28 11:23 UTC, morento101 commented on tests/test_task_182.py
> +    """ Tests for task 182 """
add whitespace after Test class doc str

2022-04-28 11:26 UTC, morento101 requested changes
Change function names and add a whitespace after Test class docstring and your branch is ready for merge

2022-04-28 11:30 UTC, morento101 commented on tests/test_task_323.py
> +    """Tests for task 323"""
Whitespace after doc str

2022-04-28 11:30 UTC, morento101 commented on tests/test_task_560.py
> +    def test_valid(self):
Whitespace after doc str

2022-04-28 11:34 UTC, morento101 approved these changes
Great job!

2022-04-28 11:34 UTC, merged